name: CI

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: justfitting
          python-version: "3.12"

      - name: Run server test suite
        shell: bash -l {0}
        run: python -m unittest discover -s server/test -p "*_test.py" -v

      - name: Install Playwright's Chromium browser
        shell: bash -l {0}
        run: python -m playwright install --with-deps chromium

      - name: Run client test suite
        shell: bash -l {0}
        run: python -m unittest discover -s client/test -p "*_test.py" -v
